---
apiVersion: v1
kind: Pod
metadata:
  namespace: demo
  annotations:
    sas.com/certificate-file-format: pem
    sas.com/owner: "49506"
    sas.com/ownerGroup: "100"
    sas.com/tls-enabled-ports: all
    sidecar.istio.io/inject: "false"
  creationTimestamp: null
  generateName: sas-launcher-2fc3f785-8c10-408c-ab54-11580ac49060-
  labels:
    controller-uid: 7edf1de2-6e8e-4def-96f9-c5b4e0af2d21
    job-name: sas-launcher-2fc3f785-8c10-408c-ab54-11580ac49060
    launcher.sas.com/job-type: compute-server
    launcher.sas.com/requested-by-client: sas.SASStudio
    launcher.sas.com/username: scnkuj
    sas.com/created-by: sas-launcher
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: sas-launcher-2fc3f785-8c10-408c-ab54-11580ac49060
    uid: 7edf1de2-6e8e-4def-96f9-c5b4e0af2d21
  selfLink: /api/v1/namespaces/d24548/pods/sas-launcher-2fc3f785-8c10-408c-ab54-11580ac49060-p2hfb
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: workload.sas.com/class
            operator: In
            values:
            - compute
        weight: 100
      - preference:
          matchExpressions:
          - key: workload.sas.com/class
            operator: NotIn
            values:
            - cas
            - connect
            - stateless
            - stateful
        weight: 50
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/mode
            operator: NotIn
            values:
            - system
  containers:
  - command:
    - /opt/sas/viya/home/bin/compsrv_start.sh
    - -serverID
    - 781399f7-4958-42b8-816f-fd58c5c24c4f
    - -context
    - 6a8f0a24-331f-4d67-a341-fa0c2e188a6b
    env:
    - name: SAS_LICENSE
      valueFrom:
        secretKeyRef:
          key: SAS_LICENSE
          name: sas-license-7hf54c2d9f
    - name: SAS_URL_SERVICE_TEMPLATE
      valueFrom:
        configMapKeyRef:
          key: SAS_URL_SERVICE_TEMPLATE
          name: sas-shared-config-62b4kfd4mf
    - name: SASCLOUDNATIVE
      value: "1"
    - name: LAUNCH_AS_JOB
      value: "true"
    - name: COMPUTESERVER_USER_CONFIG
      value: /config
    - name: COMPUTESERVER_VAR_PATH
      value: /viya
    - name: SAS_TLS_LISTENER_ENABLED
      value: "true"
    - name: SAS_LAUNCHER_SERVER_OS
      value: linux
    - name: SAS_DEPLOYMENT_ID
      value: viya
    - name: ODBCINST
      value: /opt/sas/viya/home/lib64/accessclients/odbcinst.ini
    - name: AUTOEXEC_USERMODS_FILE
      value: autoexec.sas
    - name: SAS_LAUNCHER_PROCESS_ID
      value: 2fc3f785-8c10-408c-ab54-11580ac49060
    - name: SAS_PATH_SEPARATOR
      value: /
    - name: SAS_SERVICES_URL
      value: https://d24548.ingress-nginx.vde293.unx.sas.com:443
    - name: SAS_LAUNCHER_CONSUL_URL
      value: https://sas-consul-server:8500
    - name: ODBCSYSINI
      value: /opt/sas/viya/home/lib64/accessclients/
    - name: CAS_CLIENT_SSL_CA_LIST
      value: /security/trustedcerts.pem
    - name: ODBCHOME
      value: /opt/sas/viya/home/lib64/accessclients
    - name: SAS_LANG_FILE_IN
      value: /config/startscript.sh
    - name: SAS_LAUNCHER_DEPLOYMENT_CONFIG_INSTANCE_ID
      value: default
    - name: SAS_EXT_LLP_ACCESS
      value: /opt/sas/viya/home/lib64/accessclients/lib:/opt/sas/viya/home/lib64
    - name: CONFIG_USERMODS_FILE
      value: sasv9.cfg
    - name: POSTGRES
      value: /opt/sas/viya/home/lib64
    - name: SAS_LAUNCHER_DEPLOYMENT_CONFIG_PATH
      value: /opt/sas/viya/config
    - name: SAS_SERVER_OS
      value: linux
    - name: SAS_CERTIFICATE_FILE
      value: /security/tls.crt
    - name: SAS_LAUNCHER_SAS_SERVICES_URL
      value: https://d24548.ingress-nginx.vde293.unx.sas.com:443
    - name: LAUNCH_AS_JOB
      value: "true"
    - name: SAS_DEPLOYMENT_INSTALL_PATH
      value: /opt/sas/viya/home
    - name: COMPUTESERVER_VAR_PATH
      value: /viya
    - name: SASCLOUDNATIVE
      value: "1"
    - name: SAS_LAUNCHER_DEPLOYMENT_ID
      value: viya
    - name: SASODBC
      value: /opt/sas/viya/home/lib64/accessclients/lib
    - name: SAS_DEPLOYMENT_CONFIG_INSTANCE_ID
      value: default
    - name: SAS_TRUSTED_CA_CERTIFICATES_PEM_FILE
      value: /security/trustedcerts.pem
    - name: SYB_SAS_BULK_NOTE
      value: "1"
    - name: SSL_CERT_FILE
      value: /security/trustedcerts.pem
    - name: SAS_LAUNCHER_PATH_SEPARATOR
      value: /
    - name: SAS_LAUNCHER_DEPLOYMENT_INSTALL_PATH
      value: /opt/sas/viya/home
    - name: SAS_LAUNCHER_SCRIPT_EXTENSION
      value: sh
    - name: SAS_INIT_CONFIG_KEY1
      value: config/compute/sas.compute.server/autoexec_code/contents
    - name: SAS_INIT_CONFIG_KEY2
      value: config/compute/sas.compute.server/configuration_options/contents
    - name: SAS_SCRIPT_EXTENSION
      value: sh
    - name: SAS_CONSUL_URL
      value: https://sas-consul-server:8500
    - name: SAS_CERTIFICATE_CA_CERTIFICATE_FILE
      value: /security/ca.crt
    - name: SCRIPT_USERMODS_FILE
      value: startscript.sh
    - name: SAS_INIT_CONFIG_FILE2
      value: sasv9.cfg
    - name: SAS_INIT_CONFIG_FILE3
      value: startscript.sh
    - name: SAS_INIT_CONFIG_KEY3
      value: config/compute/sas.compute.server/startup_commands/contents
    - name: SAS_CONSUL_TOKEN_PATH
      value: /config/consul.token
    - name: SAS_INIT_CONFIG_FILE1
      value: autoexec.sas
    - name: ODBCINI
      value: /opt/sas/viya/home/lib64/accessclients/odbc.ini
    - name: COMPUTESERVER_USER_CONFIG
      value: /config
    - name: SAS_CERTIFICATE_PRIVATE_KEY_FILE
      value: /security/tls.key
    - name: SAS_DEPLOYMENT_CONFIG_PATH
      value: /opt/sas/viya/config
    - name: SAS_URL_SERVICE_TEMPLATE
      value: https://@k8s.service.name@
    envFrom:
    - configMapRef:
        name: sas-access-config-hmmdg9cckh
    - configMapRef:
        name: sas-compute-server-config-f8c9c759bf
    - configMapRef:
        name: sas-tls-config-99f79t29t5
    - secretRef:
        name: sas-launcher-2fc3f785-8c10-408c-ab54-11580ac49060
    image: cr.sas.com/viya-4-x64_oci_linux_2-docker-testready/sas-programming-environment:1.9.1-20201008.1602174241580
    imagePullPolicy: IfNotPresent
    name: sas-programming-environment
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 300M
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /sasuser
      name: sasuser
    - mountPath: /sashelp
      name: sashelp
    - mountPath: /config
      name: config
    - mountPath: /viya
      name: viya
    - mountPath: /security
      name: security
    - mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts
      name: security
      subPath: cacerts
    - mountPath: /opt/sas/viya/config/etc/SASSecurityCertificateFramework/private
      name: security
      subPath: private
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-dsk2v
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: sas-image-pull-secrets-hfbbm4tfgh
  initContainers:
  - env:
    - name: KUBE_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: SAS_CERTFRAME_TOKEN_DIR
      value: /certframe-token
    - name: SAS_ADDITIONAL_CA_CERTIFICATES_DIR
      value: /customer-provided-ca-certificates
    envFrom:
    - configMapRef:
        name: sas-certframe-ingress-certificate-config-cmm2t44t88
    - configMapRef:
        name: sas-certframe-user-config-c4ch2c59m7
    - configMapRef:
        name: sas-certframe-config-ctgg29gf7t
    image: cr.sas.com/viya-4-x64_oci_linux_2-docker-testready/sas-certframe:3.7.0-20201009.1602277820958
    imagePullPolicy: IfNotPresent
    name: sas-certframe
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /certframe-token
      name: certframe-token
    - mountPath: /security
      name: security
    - mountPath: /customer-provided-ca-certificates
      name: customer-provided-ca-certificates
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-dsk2v
      readOnly: true
  - env:
    - name: SSL_CERT_FILE
      value: /security/trustedcerts.pem
    envFrom:
    - configMapRef:
        name: sas-go-config-fkkh6c52kh
    - configMapRef:
        name: sas-shared-config-62b4kfd4mf
    - secretRef:
        name: sas-consul-client
    - configMapRef:
        name: sas-compute-server-config-f8c9c759bf
    image: cr.sas.com/viya-4-x64_oci_linux_2-docker-testready/sas-config-init:1.2.6-20200928.1601307316387
    imagePullPolicy: IfNotPresent
    name: sas-config-init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /security
      name: security
    - mountPath: /config
      name: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-dsk2v
      readOnly: true
  nodeName: vde289.unx.sas.com
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 100
    runAsGroup: 100
    runAsUser: 49506
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: workload.sas.com/class
    operator: Equal
    value: compute
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: certframe-token
    secret:
      defaultMode: 420
      secretName: sas-certframe-token
  - emptyDir: {}
    name: security
  - configMap:
      defaultMode: 420
      name: sas-customer-provided-ca-certificates-km44fc867t
    name: customer-provided-ca-certificates
  - emptyDir: {}
    name: sasuser
  - emptyDir: {}
    name: sashelp
  - emptyDir: {}
    name: config
  - emptyDir: {}
    name: viya
  - name: default-token-dsk2v
    secret:
      defaultMode: 420
      secretName: default-token-dsk2v
status:
  phase: Pending
  qosClass: Burstable

